"""update schema

Revision ID: d6928ba3feec
Revises: cd2ae44307a0
Create Date: 2026-03-28 23:05:27.509627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd6928ba3feec'
down_revision: Union[str, Sequence[str], None] = 'cd2ae44307a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_status_history', sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('application_status_history', 'note')
    op.add_column('applications', sa.Column('skills', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('applications', sa.Column('resume_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('applications', sa.Column('resume_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('users', 'resume_filename')
    op.drop_column('users', 'resume_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('resume_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('applications', 'resume_filename')
    op.drop_column('applications', 'resume_path')
    op.drop_column('applications', 'skills')
    op.add_column('application_status_history', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('application_status_history', 'comment')
    # ### end Alembic commands ###
